//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusicFarmer.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuditLog1
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AuditLog1()
        {
            this.AuditLogDetails = new HashSet<AuditLogDetail>();
        }
    
        public int AuditLogId { get; set; }
        public string UserName { get; set; }
        public string EventDateUTC { get; set; }
        public string EventType { get; set; }
        public string TableName { get; set; }
        public int RecordId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AuditLogDetail> AuditLogDetails { get; set; }
    }
}
