//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Music_Farm_v2.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class comment
    {
        public int comment_id { get; set; }
        public int play_id { get; set; }
        public int user_id { get; set; }
        public string comment_text { get; set; }
    
        public virtual play_history play_history { get; set; }
        public virtual user user { get; set; }
    }
}
