//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusicFarmer.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Favourite
    {
        public int FavouriteId { get; set; }
        public int TrackId { get; set; }
        public int UserId { get; set; }
    
        public virtual Track Track { get; set; }
        public virtual User User { get; set; }
    }
}
