//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using TrackerEnabledDbContext;

namespace MusicFarmer.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using TrackerEnabledDbContext.Common.Configuration;
    using TrackerEnabledDbContext.Common.Models;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class MusicFarmerEntities : TrackerContext
    {
        public MusicFarmerEntities()
            : base("name=MusicFarmerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Album> Albums { get; set; }
        public virtual DbSet<Artist> Artists { get; set; }
        public virtual DbSet<Comment> Comments { get; set; }
        public virtual DbSet<Favourite> Favourites { get; set; }
        public virtual DbSet<PlayHistory> PlayHistories { get; set; }
        public virtual DbSet<SettingValue> SettingValues { get; set; }
        public virtual DbSet<Track> Tracks { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Vote> Votes { get; set; }
    
        public virtual ObjectResult<JukeBoxTracks_Result> JukeBoxTracks()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<JukeBoxTracks_Result>("JukeBoxTracks");
        }
    }
}
