//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Music_Farm_v2.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MusicFarmerEntities : DbContext
    {
        public MusicFarmerEntities()
            : base("name=MusicFarmerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<album> albums { get; set; }
        public virtual DbSet<artist> artists { get; set; }
        public virtual DbSet<comment> comments { get; set; }
        public virtual DbSet<play_history> play_history { get; set; }
        public virtual DbSet<track> tracks { get; set; }
        public virtual DbSet<user> users { get; set; }
        public virtual DbSet<vote> votes { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
