//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusicFarmer.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlayHistory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PlayHistory()
        {
            this.Comments = new HashSet<Comment>();
        }
    
        public int PlayHistoryId { get; set; }
        public int TrackId { get; set; }
        public int UserId { get; set; }
        public byte[] TimePlayed { get; set; }
        public bool PlayCompleted { get; set; }
        public bool IsPlaying { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comment> Comments { get; set; }
        public virtual Track Track { get; set; }
        public virtual User User { get; set; }
    }
}
