//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusicFarmer.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SettingValue
    {
        public int SettingValueId { get; set; }
        public string SettingName { get; set; }
        public int SettingValue1 { get; set; }
        public bool Active { get; set; }
    }
}
