//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Music_Farm_v2.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class track
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public track()
        {
            this.play_history = new HashSet<play_history>();
        }
    
        public int track_id { get; set; }
        public string track_name { get; set; }
        public Nullable<int> artist_id { get; set; }
        public Nullable<int> album_id { get; set; }
        public string track_URL { get; set; }
    
        public virtual album album { get; set; }
        public virtual artist artist { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<play_history> play_history { get; set; }
    }
}
